<#
.SYNOPSIS
    MarkFlow Docker Reset & Rebuild Script (PowerShell / Windows Work Machine)
    Tears down everything, force-pulls latest from GitHub, rebuilds from scratch.

.DESCRIPTION
    This script:
    1. Tears down all containers, volumes, and images
    2. Force-pulls the latest code from GitHub (hard reset to origin/main)
    3. Ensures .env is configured with work machine paths
    4. Rebuilds and starts all services

.EXAMPLE
    .\reset-markflow.ps1
    .\reset-markflow.ps1 -GPU                                        # rebuild with GPU passthrough
    .\reset-markflow.ps1 -SourceDir "C:\MyDocs" -OutputDir "D:\Output"
    .\reset-markflow.ps1 -GPU -SkipPrune                             # GPU, keep cached images
#>

param(
    [string]$RepoDir = "C:\Users\Xerxes\Projects\Doc-Conversion-2026",
    [string]$SourceDir = "C:/Users/Xerxes/T86_Work/k_drv_test",
    [string]$OutputDir = "D:/Doc-Conv_Test",
    [string]$DriveC = "C:/",
    [string]$DriveD = "D:/",
    [switch]$SkipPrune,
    [switch]$GPU
)

$ErrorActionPreference = "Stop"

Write-Host "==========================================" -ForegroundColor Cyan
Write-Host "  MarkFlow Docker Reset & Rebuild"        -ForegroundColor Cyan
Write-Host "  Machine: Work (Windows)"                -ForegroundColor Cyan
Write-Host "==========================================" -ForegroundColor Cyan

# ----------------------------------------------------------
#  Build compose args (base + optional GPU override)
# ----------------------------------------------------------
$composeArgs = @("-f", (Join-Path $RepoDir "docker-compose.yml"))

if ($GPU) {
    $gpuFile = Join-Path $RepoDir "docker-compose.gpu.yml"
    if (Test-Path $gpuFile) {
        $composeArgs += @("-f", $gpuFile)
        Write-Host "  [GPU] Including GPU compose override" -ForegroundColor Magenta
    }
    else {
        Write-Host "  [WARN] docker-compose.gpu.yml not found -- falling back to CPU only" -ForegroundColor Red
    }
}

# ----------------------------------------------------------
#  1. Tear down everything
# ----------------------------------------------------------
Write-Host ""
Write-Host "[1/5] Tearing down containers, volumes, and images..." -ForegroundColor Yellow

Push-Location $RepoDir
try {
    docker compose @composeArgs down -v 2>$null
}
catch {
    Write-Host "  No existing containers to tear down" -ForegroundColor DarkGray
}

if (-not $SkipPrune) {
    Write-Host "  Pruning unused images and build cache (preserving markflow-base)..."
    docker system prune -f --volumes
    # Remove markflow app images but NOT the base image
    docker images "markflow-*" --format "{{.Repository}}:{{.Tag}}" | Where-Object { $_ -ne "markflow-base:latest" } | ForEach-Object {
        docker rmi $_ 2>$null
    }
}

# Verify base image exists
$baseExists = docker images markflow-base:latest --format "{{.ID}}" 2>$null
if (-not $baseExists) {
    Write-Host ""
    Write-Host "  [!] markflow-base:latest not found -- building it now..." -ForegroundColor Yellow
    Write-Host "  (This is the slow step -- only needed once)"  -ForegroundColor DarkGray
    docker build -f (Join-Path $RepoDir "Dockerfile.base") -t markflow-base:latest $RepoDir
}

# ----------------------------------------------------------
#  2. Force-pull latest code from GitHub
#     git reset --hard ensures we ALWAYS get the latest,
#     even if local files diverged
# ----------------------------------------------------------
Write-Host ""
Write-Host "[2/5] Force-pulling latest code from GitHub..." -ForegroundColor Yellow

# Fetch all remote changes first
git -C $RepoDir fetch origin

# Hard reset to match remote main exactly -- no local drift
git -C $RepoDir reset --hard origin/main

# Pull to be explicit (already at origin/main, but confirms)
git -C $RepoDir pull origin main

# Show what we are now on
$commitHash = git -C $RepoDir log -1 --format="%h %s"
Write-Host "  [OK] Now at: $commitHash" -ForegroundColor Green

# ----------------------------------------------------------
#  3. Ensure .env is configured for this work machine
# ----------------------------------------------------------
Write-Host ""
Write-Host "[3/5] Configuring .env for work machine..." -ForegroundColor Yellow

$envFile = Join-Path $RepoDir ".env"

# Build .env content with work machine paths
$envLines = @(
    "# MarkFlow Environment Configuration"
    "# Work machine (Windows) - auto-generated by reset-markflow.ps1"
    ""
    "# Host paths - mounted into Docker containers"
    "SOURCE_DIR=$SourceDir"
    "OUTPUT_DIR=$OutputDir"
    "DRIVE_C=$DriveC"
    "DRIVE_D=$DriveD"
    ""
    "# Meilisearch"
    "MEILI_MASTER_KEY="
    ""
    "# Bulk conversion"
    "BULK_WORKER_COUNT=4"
    ""
    "# App"
    "SECRET_KEY=dev-secret-change-in-prod"
    "DEFAULT_LOG_LEVEL=normal"
    "DEV_BYPASS_AUTH=true"
)
$envContent = $envLines -join "`n"

# Always overwrite .env to match current parameters
Set-Content -Path $envFile -Value $envContent -Encoding UTF8 -NoNewline
Write-Host "  [OK] .env written" -ForegroundColor Green
Write-Host "    SOURCE_DIR = $SourceDir"
Write-Host "    OUTPUT_DIR = $OutputDir"

# ----------------------------------------------------------
#  4. Verify paths exist
# ----------------------------------------------------------
Write-Host ""
Write-Host "[4/5] Verifying paths..." -ForegroundColor Yellow

if (Test-Path $SourceDir) {
    $sourceCount = (Get-ChildItem $SourceDir -File -Recurse -ErrorAction SilentlyContinue | Measure-Object).Count
    Write-Host "  [OK] Source dir exists ($sourceCount files)" -ForegroundColor Green
}
else {
    Write-Host "  [!] Source dir not found: $SourceDir" -ForegroundColor Red
}

if (Test-Path $OutputDir) {
    Write-Host "  [OK] Output dir exists" -ForegroundColor Green
}
else {
    Write-Host "  [!] Output dir not found: $OutputDir - creating it..." -ForegroundColor Yellow
    New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null
    Write-Host "  [OK] Output dir created" -ForegroundColor Green
}

# ----------------------------------------------------------
#  5. Rebuild and start
# ----------------------------------------------------------
Write-Host ""
Write-Host "[5/5] Building and starting MarkFlow..." -ForegroundColor Yellow

docker compose @composeArgs up -d --build

Write-Host ""
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host "  Reset Complete!" -ForegroundColor Green
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host ""

docker compose @composeArgs ps

Write-Host ""
Write-Host "  MarkFlow UI:  http://localhost:8000"
Write-Host "  Meilisearch:  http://localhost:7700"
Write-Host "  MCP Server:   http://localhost:8001"
if ($GPU) {
    Write-Host "  GPU Mode:     ENABLED" -ForegroundColor Magenta
}
Write-Host "==========================================" -ForegroundColor Cyan

Pop-Location